version: "3"

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18-bullseye

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432

  # https://hub.docker.com/_/adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
